# Generated by Django 4.2.4 on 2023-08-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("restaurateur", "Restaurateur")]
            ),
        ),
    ]
