version: '3'
services:
  database:
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: snuffleupagus.db.elephantsql.com
      POSTGRES_DB: kkflaqym
      POSTGRES_USER: kkflaqym
      POSTGRES_PASSWORD: HK49eHib6wAUQjD4JyRfiBfN9WCwV3xs

  api:
    build: .
    command: python3 inforce/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - database