# Generated by Django 4.2.4 on 2023-08-18 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurant.menu"
            ),
        ),
    ]
